name: MLauncher Updates in All Languages [PT, EN]

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Install Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Libraries
      run: |
        python -m pip install --upgrade pip
        pip install wget
        pip install termcolor
        pip install psutil
        pip install py-cpuinfo
        pip install requests
        
    - name: Build MLauncher Artifact in PT-BR
      uses: actions/upload-artifact@v2
      with:
          name: MLauncher_Manager_Debug_PT-BR
          path: MLauncher_MCinaBox-BR.py
    - name: Build MLauncher Artifact in EN-US
      uses: actions/upload-artifact@v2
      with:
          name: MLauncher_MCinaBox_Debug_EN-US
          path: MLauncher_MCinaBox-US.py
