name: Construir Arquivo do MLauncher em PT-BR

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Instalar Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Instalar Bibliotecas
      run: |
        python -m pip install --upgrade pip
        pip install wget
        pip install termcolor
        pip install psutil
        pip install py-cpuinfo
        pip install requests
    - name: Construir Artefato do MLauncher em PT-BR
      uses: actions/upload-artifact@v2
      with:
          name: MCinaBox_Manager_Debug_PT-BR
          path: MLauncher_MCinaBox-BR.py
