name: Build MLauncher Archive in EN-US

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install libraries
      run: |
        python -m pip install --upgrade pip
        pip install wget
        pip install termcolor
        pip install psutil
        pip install py-cpuinfo
        pip install requests
    - name: Generate MLauncher artifact in EN-US
      uses: actions/upload-artifact@v2
      with:
          name: MCinaBox_Manager_Debug_EN-US
          path: MLauncher_MCinaBox-US.py
